name: complex
version: 0.6.0
author:
  - Richard Lincoln <r.w.lincoln@gmail.com>
  - Frank Moreno (@kranfix) <frankmoreno1993@gmail.com>
description: A representation of a complex number, i.e. a number which has both a real and imaginary part.
homepage: https://github.com/rwl/complex
dev_dependencies:
  test: ^1.11.1

environment:
  sdk: ">=2.7.0 <3.0.0"
