name: complex
version: 0.8.0
#author:
#  - Richard Lincoln <r.w.lincoln@gmail.com>
#  - Frank Moreno (@kranfix) <frankmoreno1993@gmail.com>
description: A representation of a complex number, i.e. a number which has both a real and imaginary part.
homepage: https://github.com/kranfix/complex

dependencies:
  meta: any

dev_dependencies:
  test: ^1.16.7
  very_good_analysis: ^5.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"
